apiVersion: compute.my.domain/v1
kind: Ec2instance
metadata:
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/managed-by: kustomize
  name: ec2instance-sample
spec:
  # TODO(user): Add fields here
